# Generated by Django 5.1.7 on 2025-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostpet",
            name="city",
            field=models.CharField(default="Maricá", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lostpet",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="lostpet",
            name="location",
            field=models.CharField(default="Rua dos Crisântemos", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lostpet",
            name="state",
            field=models.CharField(default="Rio de Janeiro", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lastseen",
            name="city",
            field=models.CharField(max_length=128),
        ),
    ]
