# Generated by Django 5.1.7 on 2025-03-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_lostpet_city_lostpet_description_lostpet_location_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LastSeen",
        ),
    ]
