# Generated by Django 5.1.7 on 2025-03-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_delete_lastseen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lostpet",
            name="location",
        ),
        migrations.AddField(
            model_name="lostpet",
            name="address",
            field=models.CharField(
                default="Rua dos Crisântemos", max_length=255, verbose_name="address"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="city",
            field=models.CharField(max_length=128, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="description",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "Unknown"), (1, "Male"), (2, "Female")],
                default=0,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="name",
            field=models.CharField(
                default="Unknown", max_length=100, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="predominant_color",
            field=models.CharField(
                max_length=50, null=True, verbose_name="predominant color"
            ),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="species",
            field=models.SmallIntegerField(
                choices=[(0, "Other"), (1, "Dog"), (2, "Cat"), (3, "Bird")],
                default=0,
                verbose_name="species",
            ),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="state",
            field=models.CharField(max_length=64, verbose_name="state"),
        ),
        migrations.AlterField(
            model_name="lostpet",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Lost"), (1, "Found")], default=0, verbose_name="register"
            ),
        ),
    ]
